name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://createfeed.fivefilters.org/extract.php?url=https%3A%2F%2Fprudhvi0001.github.io%2FBlogs%2F&in_id_or_class=archive__item-title&max=5&order=document"
